HomesteadForum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('forum.urls')),
]

accounts/urls.py
from django.urls import path
from .views import SignUpView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

forum/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'forum'

urlpatterns = [
    path('', views.forum_home_view, name='home'),
    path('forum/<int:forum_id>/', views.forum_view, name='forum'),
    path('post/<int:post_id>/', views.post_view, name='post'),
    path('post/new/', views.create_post, name='new_post'),
    path('post/<int:post_id>/edit', views.edit_post, name='edit_post'),
    path('comment/new/', views.create_comment, name='new_comment'),
    path('comment/<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('profile/<str:username>/', views.user_profile_view, name='user_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username


class UserProfile(models.Model):
    user = models.OneToOneField(
        "accounts.CustomUser",
        on_delete=models.CASCADE,
    )

    # add additional fields for UserProfile
    location = models.CharField(null=True, blank=True)
    avatar = models.ImageField(null=True, upload_to='avatars')

    def __str__(self):
        return f"Profile for {self.user.username}"

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"


@receiver(post_save, sender=CustomUser)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    UserProfile.objects.get_or_create(user=instance)

forum/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class ForumGroup(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Forum(models.Model):
    name = models.CharField(null=False, blank=False, max_length=500)
    description = models.CharField(null=True, blank=True,max_length=2000)
    forum_group = models.ForeignKey(ForumGroup, null=False, blank=False, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Post(models.Model):
    forum = models.ForeignKey(Forum, null=False, blank=False, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(null=False, blank=False, max_length=2000)
    text = models.TextField(null=False, blank=False)
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(default=timezone.now)


class Comment(models.Model):
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(null=False, blank=False)
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(default=timezone.now)

accounts/forms.py
from django.contrib.auth.forms import AdminUserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(AdminUserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

forum/forms.py
from .models import Post, Comment
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm


# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import ForumGroup, Forum, Post, Comment
from accounts.models import UserProfile
from .forms import PostForm, CommentForm

def forum_home_view(request):
    context = {}
    forum_groups = ForumGroup.objects.all()
    forums = Forum.objects.all()

    context['forum_groups'] = forum_groups
    context['forums'] = forums
    return render(request, 'forum/home.html', context)


def forum_view(request, forum_id):
    context = {}
    forum = get_object_or_404(Forum, pk=forum_id)
    forum_posts = Post.objects.filter(forum__id=forum_id)

    context['forum'] = forum
    context['forum_posts'] = forum_posts
    context['post_count'] = forum_posts.count()

    return render(request, 'forum/forum.html', context)


def post_view(request, post_id):
    context = {}
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post__id=post_id)
    context['post'] = post
    context['comments'] = comments
    context['comment_count'] = comments.count()

    return render(request, 'forum/post.html', context)


def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.forum = get_object_or_404(Forum, pk=request.POST.get('forum_id'))
            post.title = form.cleaned_data["title"]
            post.author = request.user
            post.text = form.cleaned_data["text"]
            post.save()
            return redirect('forum:post', post_id=post.pk)

    else:
        context = {}
        context['form'] = PostForm()
        forum = get_object_or_404(Forum, pk=request.GET['forum_id'])
        context['forum'] = forum

        return render(request, 'forum/edit_post.html', context)


def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save(commit=False)
            post.title = form.cleaned_data["title"]
            post.text = form.cleaned_data["text"]
            post.save()
            return redirect('forum:post', post_id=post.pk)

    else:
        context = {}
        context['form'] = PostForm(instance=post)
        context['forum'] = get_object_or_404(Forum, pk=post.forum.id)

    return render(request, 'forum/edit_post.html', context)


def create_comment(request):
    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Post, pk=request.POST.get('post_id'))
            comment.text = form.cleaned_data["text"]
            comment.author = request.user
            comment.save()
            return redirect('forum:post', post_id=comment.post.id)

    else:
        context = {}
        context['form'] = CommentForm()
        context['post'] = get_object_or_404(Post, pk=request.GET['post_id'])

        return render(request, 'forum/edit_comment.html', context)


def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.text = form.cleaned_data["text"]
            comment.save()
            return redirect('forum:post', post_id=comment.post.id)

    else:
        context = {}
        context['form'] = CommentForm(instance=comment)
        context['post'] = get_object_or_404(Forum, pk=comment.post.id)

    return render(request, 'forum/edit_comment.html', context)


def user_profile_view(request, username):
    context = {}
    context['profile'] = get_object_or_404(UserProfile, user_id=request.user.id)

    return render(request, 'forum/user_profile.html', context)

forum/templates/forum/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homestead Forum</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'forum/img/favicon_placeholder.png' %}">
    {% block extrahead %}{% endblock %}
</head>
<body>
    <a href="{% url 'forum:home' %}">Home</a>
    {% if user.is_authenticated %}
    <a href="{% url 'forum:user_profile' username=user.username %}" style="float: right;">{{ user.username }}</a>

    <form action="{% url 'logout' %}" method="post" style="float: right;">
        {% csrf_token %}
        <button type="submit">Log Out</button>
    </form>
    {% else %}
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

forum/templates/forum/edit_comment.html
{% extends "forum/base.html" %}

{% block content %}
<p><a href="{% url 'forum:post' post_id=post.pk %}">Back to post</a></p>
<h1>Add Comment for {{ post.title }}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="post_id" value="{{ post.pk }}">   
    <button type="submit">Comment</button>
</form>
{% endblock %}

forum/templates/forum/edit_post.html
{% extends "forum/base.html" %}

{% block content %}
<p><a href="{% url 'forum:forum' forum_id=forum.pk %}">Back to {{ forum.name }}</a></p>
<h1>{{ post.title }}</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="hidden" name="forum_id" value="{{ forum.pk }}">
    <button type="submit">Save Post</button>
</form>
{% endblock %}

forum/templates/forum/forum.html
{% extends "forum/base.html" %}

{% block content %}
<h1>{{ forum.name }}</h1>

{% if user.is_authenticated %}
<a href="{% url 'forum:new_post' %}?forum_id={{ forum.pk }}">Create Post</a>
{% endif %}

{% if post_count > 0 %}
    {% for post in forum_posts %}
    <a href="{% url 'forum:post' post_id=post.pk %}"><h3>{{ post.title }}</h3></a>
    {% endfor %}
{% else %}
    <h2>No posts yet!</h2>
{% endif %}
{% endblock %}

forum/templates/forum/home.html
{% extends "forum/base.html" %}

{% block content %}    
    {% if user.is_authenticated %}
    <h1>Welcome to Homestead Forum, {{ user.username }}!</h1>
    {% else %}
    <h1>Welcome to Homestead Forum!</h1>
    {% endif %}

    {% for forum_group in forum_groups %}
        <h2>{{ forum_group.name }}</h2>
        {% for forum in forums %}
            {% if forum.forum_group.id == forum_group.id %}
                <h3><a href="{% url 'forum:forum' forum_id=forum.pk %}">{{ forum.name }}</a></h3>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endblock %}

forum/templates/forum/post.html
{% extends "forum/base.html" %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'forum/css/post.css' %}">
{% endblock %}


{% block content %}
<p><a href="{% url 'forum:forum' forum_id=post.forum.pk %}">Back to {{ post.forum.name }}</a></p>
<h1>{{ post.title }}</h1>

<p>{{ post.text }}</p>
<img src=""> <p>{{ post.author.username }}</p>

{% if user.is_authenticated %}
    {% if post.author.username == user.username %}
    <a href="{% url 'forum:edit_post' post_id=post.pk %}">Edit Post</a>
    {% endif %}

    <p><a href="{% url 'forum:new_comment' %}?post_id={{ post.pk }}">Add Comment</a></p>
{% endif %}

{% if comment_count > 0 %}
    {% for comment in comments %}
        <article class="post-comment">
            <div class="message-inner">
                <div class="message-cell-user">
                    <div class="message-avatar">
                        <img class="avatar" src="{{ comment.author.userprofile.avatar.url }}">
                    </div>
                    <div class="message-userDetails">
                        <p>{{ comment.author.username }}</p>
                        <p>Location: {{ comment.author.userprofile.location }}</p>
                        <p>Posts: {{ comment.author.post_set.count }}</p>
                        <p>Comments: {{ comment.author.comment_set.count }}</p>
                    </div>
                    
                </div>
                <div class="message-content" >
                    <p>{{ comment.text }}</p>
                    <footer class="message-footer">
                        {% if user.is_authenticated %}
                            {% if comment.author.username == user.username %}
                                <p><a href="{% url 'forum:edit_comment' comment_id=comment.pk %}">Edit Comment</a></p>
                            {% endif %}
                        {% endif %}
                    </footer>                    
                </div>                
            </div>           
        </article>
    {% endfor %}
{% else %}
<h2>No Comments Yet!</h2>
{% endif %}
{% endblock %}

forum/templates/forum/user_profile.html
{% extends "forum/base.html" %}

{% block content %}

<h1>{{ user.username }}'s Profile</h1>

<h3>Location: {{ profile.location }}</h3>

<img src="{{ profile.avatar.url }}">

<p>Posts: {{ user.post_set.count }}</p>
<p>Comments: {{ user.comment_set.count }}</p>

{% endblock %}